Repository scenchive/Scenchive_BE, pull requests merged in 2023-05, with the labels that each got.

#1 Feat: 로그인, 회원가입 기능 구현
  Scenchive/build.gradle
  Scenchive/src/main/java/com/example/scenchive/ScenchiveApplication.java
  Scenchive/src/main/java/com/example/scenchive/domain/BaseTimeEntity.java
  Scenchive/src/main/java/com/example/scenchive/domain/Board.java
  Scenchive/src/main/java/com/example/scenchive/domain/BoardRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/Member.java
  Scenchive/src/main/java/com/example/scenchive/domain/MemberRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/boardType.java
  Scenchive/src/main/java/com/example/scenchive/service/LoginService.java
  Scenchive/src/main/java/com/example/scenchive/service/MemberService.java
  Scenchive/src/main/java/com/example/scenchive/service/NotCorrespondingEmailException.java
  Scenchive/src/main/java/com/example/scenchive/web/LoginController.java
  Scenchive/src/main/java/com/example/scenchive/web/LoginForm.java
  Scenchive/src/main/java/com/example/scenchive/web/MemberController.java
  Scenchive/src/main/java/com/example/scenchive/web/MemberForm.java
  Scenchive/src/main/resources/application.properties
  Scenchive/src/test/java/com/example/scenchive/service/MemberServiceTest.java
Labels: enhancement

#4 Feat: 게시글, 게시판 구현 완료
  Scenchive/src/main/java/com/example/scenchive/board/controller/BoardController.java
  Scenchive/src/main/java/com/example/scenchive/board/dto/BoardListResponseDto.java
  Scenchive/src/main/java/com/example/scenchive/board/dto/BoardSaveRequestDto.java
  Scenchive/src/main/java/com/example/scenchive/board/dto/BoardUpdateRequestDto.java
  Scenchive/src/main/java/com/example/scenchive/board/repository/Board.java
  Scenchive/src/main/java/com/example/scenchive/board/repository/BoardRepository.java
  Scenchive/src/main/java/com/example/scenchive/board/repository/boardType.java
  Scenchive/src/main/java/com/example/scenchive/board/service/BoardService.java
  Scenchive/src/main/java/com/example/scenchive/domain/Board.java
  Scenchive/src/main/java/com/example/scenchive/domain/BoardRepository.java
  Scenchive/src/main/java/com/example/scenchive/member/controller/LoginController.java
  Scenchive/src/main/java/com/example/scenchive/member/controller/MemberController.java
  Scenchive/src/main/java/com/example/scenchive/member/dto/LoginForm.java
  Scenchive/src/main/java/com/example/scenchive/member/dto/MemberForm.java
  Scenchive/src/main/java/com/example/scenchive/member/repository/Member.java
  Scenchive/src/main/java/com/example/scenchive/member/repository/MemberRepository.java
  Scenchive/src/main/java/com/example/scenchive/member/service/LoginService.java
  Scenchive/src/main/java/com/example/scenchive/member/service/MemberService.java
  Scenchive/src/main/java/com/example/scenchive/member/service/NotCorrespondingEmailException.java
  Scenchive/src/test/java/com/example/scenchive/service/MemberServiceTest.java
Labels: enhancement

#5 커뮤니티 구현 완료
  Scenchive/src/main/java/com/example/scenchive/board/controller/BoardController.java
  Scenchive/src/main/java/com/example/scenchive/board/repository/Board.java
  Scenchive/src/main/java/com/example/scenchive/board/repository/BoardRepository.java
  Scenchive/src/main/java/com/example/scenchive/board/repository/boardType.java
  Scenchive/src/main/java/com/example/scenchive/board/service/BoardService.java
  Scenchive/src/main/java/com/example/scenchive/member/controller/LoginController.java
  Scenchive/src/main/java/com/example/scenchive/member/controller/MemberController.java
  Scenchive/src/main/java/com/example/scenchive/member/exception/NotCorrespondingEmailException.java
  Scenchive/src/main/java/com/example/scenchive/member/service/LoginService.java
Labels: enhancement

#13 [Feat] 회원가입 키워드 설문조사 1차 구현
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PTag.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Perfume.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTag.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/SurveyController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/dto/SurveyUserTagDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/UserTag.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/UserTagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Utag.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/UtagType.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/SurveyService.java
  Scenchive/src/test/java/com/example/scenchive/controller/CommentControllerTest.java
  Scenchive/src/test/java/com/example/scenchive/service/MemberServiceTest.java
  Scenchive/src/test/java/com/example/scenchive/service/PerfumeServiceTest.java
Labels: enhancement

#17 [Feat] 향수 시향 후기 및 평가 서비스 (1차 구현)
  Scenchive/src/main/java/com/example/scenchive/domain/board/controller/BoardController.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/dto/BoardResponseDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/repository/Board.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/repository/exception/MemberException.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/repository/exception/MemberExceptionType.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/repository/exception/NotCorrespondingEmailException.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTag.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/LoginController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/LoginService.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/dto/ReviewDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/repository/Review.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/repository/ReviewRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
  Scenchive/src/test/java/com/example/scenchive/service/PerfumeServiceTest.java
Labels: feat🔥

#18 Feature/14 profile recommend jeongin
  Scenchive/src/main/java/com/example/scenchive/domain/board/repository/exception/MemberException.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/repository/exception/MemberExceptionType.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PersonalDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PTagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/LoginController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/SurveyController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/exception/NotCorrespondingEmailException.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/UserTagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/LoginService.java
  Scenchive/src/main/resources/application.properties
  Scenchive/src/test/java/com/example/scenchive/service/PerfumeServiceTest.java
Labels: feat🔥

#19 Fix/12 survey jeongin
  Scenchive/src/main/java/com/example/scenchive/domain/board/repository/BoardRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/SurveyController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/dto/UtagDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/MemberRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/UserTagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/UtagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/SurveyService.java
Labels: feat🔥, fix🔩
