Repository scenchive/Scenchive_BE, pull requests merged in 2023-07, with the labels that each got.

#57 [FIX] 키워드 필터링 무한 스크롤 페이징
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeResponseDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
  Scenchive/src/main/resources/application.properties
Labels: fix🔩, add🔦

#58 [Fix] 키워드 필터링 무한 스크롤 페이징 오류 수정
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeResponseDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTag.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTagId.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/perfumeMarkedId.java
  Scenchive/src/main/resources/application.properties
Labels: fix🔩

#62 [Feat] JWT 토큰 추가
  Scenchive/build.gradle
  Scenchive/src/main/java/com/example/scenchive/config/CorsConfig.java
  Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/AuthController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/LoginController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MemberController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/ProfileController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/dto/AuthorityDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/dto/LoginForm.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/dto/MemberForm.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/dto/TokenDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/exception/DuplicateMemberException.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Authority.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/MemberRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/CustomUserDetailsService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/LoginService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/util/SecurityUtil.java
  Scenchive/src/main/java/com/example/scenchive/jwt/JwtAccessDeniedHandler.java
  Scenchive/src/main/java/com/example/scenchive/jwt/JwtAuthenticationEntryPoint.java
  Scenchive/src/main/java/com/example/scenchive/jwt/JwtFilter.java
  Scenchive/src/main/java/com/example/scenchive/jwt/JwtSecurityConfig.java
  Scenchive/src/main/java/com/example/scenchive/jwt/TokenProvider.java
  Scenchive/src/main/resources/application.properties
Labels: feat🔥

#63 [Fix] JWT 관련 코드 수정
  Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/controller/BoardController.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/dto/BoardSaveRequestDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java
  Scenchive/src/main/resources/application.properties
Labels: fix🔩

#65 [Add] 향수 프로필 북마크한 향수 및 유사 향수 조회 - 무한 스크롤 페이징
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/dto/BookmarkPerfumeResponseDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
Labels: fix🔩, add🔦

#67 [Fix] 댓글 기능 Jwt 토큰 추가
  Scenchive/src/main/java/com/example/scenchive/domain/comment/controller/CommentController.java
  Scenchive/src/main/java/com/example/scenchive/domain/comment/service/CommentService.java
Labels: fix🔩, add🔦

#68 [Fix] 향수 프로필 북마크한 향수와 유사한 향수 개수 반환
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
Labels: fix🔩

#69 [Fix] 향수 프로필 북마크한 향수와 유사한 향수 개수 반환
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
Labels: fix🔩

#70 [Fix] 검색 결과 반환값 수정
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/BrandDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchListDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchPerfumeDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Brand.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java
Labels: fix🔩

#71 [Fix] 게시판 조회 페이징 구현
  Scenchive/src/main/java/com/example/scenchive/domain/board/controller/BoardController.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/dto/BoardListResponseDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java
Labels: fix🔩, add🔦

#75 [Fix] 향수 리뷰 기능 수정 및 사용자 닉네임 조회 기능 추가
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MemberController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/CustomUserDetailsService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/dto/ReviewDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
Labels: feat🔥, fix🔩

#76 [Feat] 로그아웃 구현
  Scenchive/build.gradle
  Scenchive/src/main/java/com/example/scenchive/config/RedisConfig.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/AuthController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java
  Scenchive/src/main/java/com/example/scenchive/jwt/JwtFilter.java
  Scenchive/src/main/java/com/example/scenchive/jwt/TokenProvider.java
  Scenchive/src/main/resources/application.properties
Labels: feat🔥, add🔦

#77 [Fix] 개별 게시글 조회 시 날짜 반환형태 수정
  Scenchive/src/main/java/com/example/scenchive/domain/board/dto/BoardResponseDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java
  Scenchive/src/main/resources/application.properties
Labels: fix🔩

#78 [Fix] 댓글 조회 시 날짜 반환형태 수정
  Scenchive/src/main/java/com/example/scenchive/domain/comment/service/CommentService.java
Labels: fix🔩
