Repository scenchive/Scenchive_BE, pull requests merged in 2023-09, with the labels that each got.

#95 [Add] 브랜드명 한글 번역 변수 추가
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/MainPerfumeDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PersonalDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/dto/BookmarkPerfumeDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
  Scenchive/src/main/resources/application.properties
Labels: add🔦

#96 [Fix] 게시물 저장 시 이미지 추가 기능 구현
  Scenchive/.gitignore
  Scenchive/src/main/java/com/example/scenchive/config/S3Config.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/controller/BoardController.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/repository/Board.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/service/S3Uploader.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/BrandRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeRepository.java
  Scenchive/src/main/resources/application.properties
  Scenchive/src/test/java/com/example/scenchive/service/MemberServiceTest.java
Labels: add🔦

#97 [Fix] 메인화면 향수 추천 한글 브랜드명 반환 오류 해결
  Scenchive/build.gradle
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/BrandRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/repository/ReviewRepository.java
Labels: fix🔩

#98 DTfix: DTO 한글 번역 변수 순서 수정
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
Labels: fix🔩

#100 [Feat] 브랜드 한글 검색 기능 추가
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/BrandRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java
  Scenchive/src/main/resources/application.properties
Labels: feat🔥

#104 [Fix] 카테고리별 게시판 조회 내림차순 정렬
  Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java
Labels: fix🔩

#105 [Fix] 향수 프로필 추천 향수 최대 개수 설정
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
Labels: fix🔩

#107 [Add] 커뮤니티 게시글 수 반환
  Scenchive/src/main/java/com/example/scenchive/domain/board/controller/BoardController.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/dto/TotalBoardResponseDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java
  Scenchive/src/main/resources/application.properties
Labels: add🔦

#108 [Fix] 메인화면 향수 추천 기능 수정
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/MainPerfumeDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
Labels: fix🔩

#109 [Fix] 커뮤니티 게시글 수 반환 수정
  Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java
Labels: fix🔩

#111 [Fix] 향수 프로필 유사 향수 추천 개수 제한
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
  Scenchive/src/main/resources/application.properties
Labels: fix🔩

#112 [Feat] 향수 전체 정보 반환
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeFullInfoDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
Labels: feat🔥

#114 [Fix] 향수 별점순 정렬 기능 수정
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
Labels: fix🔩

#115 [Fix] 개별 향수 평가 평점평균 수정
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
Labels: fix🔩
