Repository scenchive/Scenchive_BE, pull requests merged in 2023-06, with the labels that each got.

#25 메인화면 향수 추천 기능 구현
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
Labels: feat🔥

#29 [Feat] 브랜드별 향수 조회 기능 구현 및 CORS 설정 추가
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PersonalDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchPerfumeDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTag.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/LoginController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MemberController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/ProfileController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/SurveyController.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java
  Scenchive/src/main/resources/application.properties
Labels: feat🔥, add🔦

#32 [Add] 향수 시향 후기 및 평가 서비스 (2차 구현)
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Perfume.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/dto/ReviewDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/dto/ReviewListResponseDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/repository/Review.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/repository/ReviewRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
Labels: add🔦

#35 [Feat] 필터 검색 키워드 반환
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PTagDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PTag.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PTagType.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTag.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
Labels: feat🔥

#37 [Feat] 북마크 향수 조회 및 유사 향수 추천 기능 구현
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/dto/BookmarkPerfumeDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/perfumeMarkedRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
Labels: feat🔥

#38 [Feat] 개별 향수 평가 평점평균 기능 구현
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/dto/PerfumeRatingDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/dto/ReviewDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/repository/Review.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/repository/ReviewRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
  Scenchive/src/main/resources/application.properties
Labels: feat🔥

#41 [Fix] 향수 및 브랜드 검색 누락 문제 해결
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/BrandRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/ProfileController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/ProfileService.java
Labels: fix🔩

#42 [Feat] 개별 향수 노트 정보 조회 (1차 구현)
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/dto/NotesInfoDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/dto/NotesInfoResponse.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/repository/Perfumenote.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumenoteRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/repository/Perfumescent.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumescentRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/service/NotesService.java
  Scenchive/src/main/resources/application.properties
Labels: feat🔥

#43 [Fix] 개별 향수 노트 정보 조회 (2차 구현)
  Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Perfume.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/repository/Perfumenote.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/repository/Perfumescent.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumescentId.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumescentRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/info/service/NotesService.java
  Scenchive/src/main/resources/application.properties
Labels: fix🔩

#45 [Add] 온라인 최저가 쇼핑몰 연결 서비스 (2차 구현)
  Scenchive/build.gradle
  Scenchive/src/main/java/com/example/scenchive/domain/shopping/dto/ItemDto.java
Labels: fix🔩, add🔦

#47 [Feat] 향수 북마크 유무 확인
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
Labels: feat🔥

#49 [Fix] 추천 향수 반환 시 중복 향수 제거
  Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/utils/DeduplicationUtils.java
Labels: fix🔩

#52 [Feat] 향수 프로필 키워드 수정 기능 구현
  Scenchive/src/main/java/com/example/scenchive/domain/member/controller/ProfileController.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/dto/UtagDtoList.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/UserTagRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/ProfileService.java
Labels: feat🔥

#53 [Feat] 커뮤니티 무한 댓글(대댓글) 구현
  Scenchive/src/main/java/com/example/scenchive/domain/board/repository/Board.java
  Scenchive/src/main/java/com/example/scenchive/domain/comment/controller/CommentController.java
  Scenchive/src/main/java/com/example/scenchive/domain/comment/dto/CommentDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/comment/dto/CommentRequest.java
  Scenchive/src/main/java/com/example/scenchive/domain/comment/repository/Comment.java
  Scenchive/src/main/java/com/example/scenchive/domain/comment/repository/CommentRepository.java
  Scenchive/src/main/java/com/example/scenchive/domain/comment/service/CommentService.java
Labels: feat🔥

#55 [Fix] 향수 검색 시 중복 문제 해결 및 향수 아이디 반환
  Scenchive/build.gradle
  Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchPerfumeDto.java
  Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/exception/NotFoundMemberException.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/LoginService.java
  Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java
Labels: fix🔩
